import type { WorkflowRuntimeBundle } from "../types/orchestrator";

export const runtimeBundle: WorkflowRuntimeBundle = {
  goal: {
    goal_id: "goal_100",
    goal_text: "Map Bayesian evidence",
    success_definition: ["Every conclusion cites evidence"],
    non_goals: [],
    constraints: {},
    context_scope: [],
    approval_policy: {},
    budget: { max_iterations: 30 },
    created_at: "100",
  },
  workflow: {
    workflow_id: "wf_100",
    goal_id: "goal_100",
    version: 1,
    parent_version: null,
    status: "completed",
    global_context: {},
    control_policy: {
      max_parallel_steps: 1,
      replan_on_verification_fail: true,
      max_patch_chain: 1,
    },
    steps: [{
      step_id: "S001",
      title: "Research goal",
      kind: "research",
      agent_type: "research_subagent",
      mode: "read_only",
      task: "Map Bayesian evidence",
      inputs: { question: "Map Bayesian evidence" },
      dependencies: [],
      acceptance_criteria: ["Every conclusion cites evidence"],
      goal_alignment: {
        success_clauses: [1],
        why_necessary: "Research satisfies the goal",
      },
      retry_policy: { max_attempts: 1, backoff_ms: 0 },
      status: "verified",
    }],
    created_by: "orchestrator@template",
    created_at: "100",
  },
  run: {
    run_id: "run_100",
    workflow_id: "wf_100",
    workflow_version: 1,
    status: "succeeded",
    started_at: "100",
    ended_at: "200",
    active_step_ids: [],
    worktree_map: {},
    metrics: {},
    context_digest_version: 1,
  },
  registry: {
    agents: {
      research_subagent: {
        agent_type: "research_subagent",
        allowed_tools: ["vector_search", "web_search"],
        denied_tools: [],
        default_mode: "read_only",
        max_parallelism: 1,
        can_delegate: false,
      },
    },
  },
  dispatches: [{
    step_id: "S001",
    attempt: 1,
    task_id: "workflow__run_100__S001__attempt_1",
    status: "reported",
    detail: "research result recorded",
  }],
  artifacts: [
    {
      artifact_id: "working-result",
      type: "other",
      uri: ".dualtrack/research/results/workflow__run_100__S001__attempt_1/result.md",
      hash: "sha256:working",
      mime_type: "text/markdown",
      producer_step_id: "S001",
      retention_policy: "workflow",
      created_at: "200",
    },
    {
      artifact_id: "semantic-result",
      type: "other",
      uri: ".dualtrack/memory/semantic/workflows/wf_100/run_100.md",
      hash: "sha256:semantic",
      mime_type: "text/markdown",
      producer_step_id: "S001",
      retention_policy: "workflow",
      created_at: "200",
    },
  ],
  step_reports: [{
    report_id: "report_run_100_S001",
    step_id: "S001",
    attempt: 1,
    status: "completed",
    summary: "Research contract passed",
    artifacts: [],
    evidence: [{
      file: ".dualtrack/research/results/workflow__run_100__S001__attempt_1/context.json",
      lines: [],
      claim: "Evidence exists",
    }],
    risks: [],
    blocked_by: [],
    suggested_next_steps: [],
    resource_usage: {},
    confidence: 0.9,
  }],
  verification_findings: [{
    verification_id: "verify_run_100_S001_1",
    level: "step",
    target: "S001",
    result: "pass",
    failed_clauses: [],
    reason_code: "acceptance_criterion_checked",
    summary: "Every conclusion cites evidence",
    evidence_refs: ["working-result"],
    minimal_fix_surface: [],
  }],
  updated_at: "200",
};
